[project]
name = "multilingual-chat"
version = "0.1.0"
description = "Have a chat in multiple languages at once."
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "anthropic>=0.40.0",
    "streamlit>=1.40.2",
]
